import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import Header from "../components/Header";
import Hero from "../components/Hero";
import Stats from "../components/Stats";
import Boost from "../components/Boost";
import Footer from "../components/Footer";
import Search from "../components/Search";

export default function Home() {
  return (
    <>
      <Head>
        <title>Shortly - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main className={styles.main}>
        <Hero />
        <Search />
        <Stats />
        <Boost />
      </main>

      <Footer />
    </>
  );
}
